Fix and optim `dropdown-menu.svg`
radix-ui/website pull request #309
Opened 2021-12-13 19:50 UTC by httpstersk

I've centered an arrow in the `dropdown-menu.svg` file on homepage. It was a little bit off. I've also optimized the file via `SVGO` (54kb → 33kb).

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [ ] Include the URL where we can test the change in the body of your PR.

This pull request:

- [ ] Fixes a bug
- [ ] Adds additional features/functionality
- [x] Updates documentation or example code
- [ ] Other

2021-12-23 21:21 UTC, vladmoroz requested changes
Hey, thanks for the contribution. Could you please make sure that the SVG appears exactly the same?

Currently, the drop shadow in the new SVG seems stronger.

https://www.radix-ui.com/marketing/dropdown-menu.svg
https://radix-website-git-fork-httpstersk-svg-fix-and-optim.modulz-deploys.com/marketing/dropdown-menu.svg

2021-12-30 21:18 UTC, httpstersk commented
Hi Vlad.

The Figma export messed up the shadow. It should be ok now 👇
https://radix-website-cuw11v21r.modulz-deploys.com/marketing/dropdown-menu.svg

2022-01-26 20:38 UTC, vladmoroz approved these changes

2022-01-26 20:38 UTC, merged

2022-01-26 20:38 UTC, vladmoroz commented
Thank you Lubos!